routes/web.php
<?php


use App\User;
use Illuminate\Support\Facades\Notification;
use Spatie\CalendarLinks\Link;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('locale')->group(function(){

    Route::get('welcome/{lang}','LocalController@index');
    Route::get('/', "WelcomeController@index");



    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/dashboard', function(){
        return view("layouts.dashboard");
    });

    Route::post('temp','FileUploaderController@store')->name('files.store');
    Route::get('files/{document}','FileDownloaderController@download')->name('files.download');
    Auth::routes(['verify' => true]);
    Route::group(["prefix"=>"admin_102019_xyz"],function(){
        Auth::routes(['verify' => true]);
    });

    Route::get('jobs/{job}/apply_form','JobApplicationController@show')->name('jobs.apply_form_for_doctors');
    Route::post('jobs/{job}/apply','JobApplicationController@apply')->name('jobs.apply_for_doctors');

    Route::group(["middleware"=>["auth"]],function (){
        //For doctor portal




    });
    Route::group(['middleware'=>['auth','Admin'], "prefix"=>"admin_102019_xyz"],function(){

        Route::get('/',"HomeController@index");//TODO: Check this route
        Route::get('/dash',"AdminDashboardController@index")->name('admin.dashboard');

        //jobs

        Route::get('jobs/{job}/notifications_form','JobNotificationController@show')->name('jobs.notifications_form');

        Route::get('job_applications','JobApplicationController@index')->name('jobs.applications');

        Route::get('jobs/{job}/apply_form','JobApplicationController@show')->name('jobs.apply_form');
        Route::resource('jobs','JobController');
        Route::get('create_jobs','JobController@create')->name('jobs.create');
        Route::get('list_jobs','JobController@index')->name('jobs.list');
        Route::get('overview_jobs','JobController@index')->name('jobs.overview');//TODO: check if we need this route, or change it

        Route::post('jobs/{job}/send_notification','JobNotificationController@notifyDoctors')->name('jobs.send_notifications');
        Route::post('practices/{practice}/send_notification','JobNotificationController@sendVerificationToPractice')->name('jobs.send_notification_to_practice');


        //practices
        route::get('practice_jobs_view','JobNotificationController@verif_form')->name('practices.jobs_view');

        route::get('practices/{practice}/jobs/{job}/confirm','PracticeMissionConfirmController@confirm_mission')->name('practices.confirm_mission');
        route::get('practices/{practice}/confirm_many_missions','PracticeMissionConfirmController@confirm_missions')->name('practices.confirm_missions');

        Route::resource('practices','PracticeController');
        route::get('create_practice','PracticeController@create')->name('practices.create');
        route::get('list_practices','PracticeController@index')->name('practices.list');




        //doctors

        Route::get('doctors_notifications','DoctorsNotificationController@notifications')->name('doctors.notifications.view');
        Route::post('doctors_notifications','DoctorsNotificationController@sendNotifications')->name('doctors.notifications.send');


        Route::resource('doctors','DoctorController');
        route::get('create_doctor','DoctorController@create')->name('doctors.create');
        //services
        Route::post('services/{service}/clone','ServiceAreaController@clone')->name('services.clone');

        Route::resource('services','ServiceAreaController');
        route::get('create_service','ServiceAreaController@create')->name('services.create');
        route::get('list_services','ServiceAreaController@index')->name('services.list');
        Route::resource('users','UserManagerController');


        Route::resource('specialities','SpecialityController');

        Route::resource('recipients','RecipientsController');
        Route::resource('recipients-2nd','Recipients2ndController');

        Route::resource('hotels','HotelController');

        Route::resource('facilities','FacilityController');


        Route::get('calendar','CalendarController@index')->name('calendar.view');

        Route::get('templates','EmailTemplateController@index')->name('templates.index');
        Route::get('create_template','EmailTemplateController@create')->name('templates.create');
        Route::get('edit_template/{template}','EmailTemplateController@edit')->name('templates.edit');
        Route::post('store_template','EmailTemplateController@store')->name('templates.store');
        Route::post('update_template','EmailTemplateController@update')->name('templates.update');
        Route::get('templates/{template}/files/{template_file}/delete','EmailTemplateController@deleteFile')->name('templates.files.delete');


        Route::get('send_email_form','SendEmailController@show')->name('email.show');
        Route::post('send_email','SendEmailController@send')->name('email.send');

        Route::get('send_service_email_form','SendServiceEmailController@show')->name('service_email.show');
        Route::post('send_service_email','SendServiceEmailController@send')->name('service_email.send');


        Route::get('jobs-fulfillment','JobFulfillmentController@index')->name('jobs.fulfillment');
        Route::get('jobs-fulfillment/{job}','JobFulfillmentController@show')->name('jobs.fulfillment.show');
        Route::get('jobs-fulfillment/{job}/send-pdf','JobFulfillmentController@sendPDF')->name('jobs.fulfillment.send-pdf');

        Route::get('sent-emails','SentEmailsController@index')->name('sent-emails.index');

        Route::get('practice_jobs_new','JobNotificationController@verificationNew')->name('practices.verification_new');
        Route::post('practice_jobs_new','JobNotificationController@verificationNewSend')->name('practices.verification_new.send');

    });




});


Route::get('links',function (){

return \App\Models\Job::with(["applications"])->paginate(10);

    $from = DateTime::createFromFormat('Y-m-d H:i', '2018-02-01 09:00');
    $to = DateTime::createFromFormat('Y-m-d H:i', '2018-02-01 18:00');

    $link = Link::create('Sebastian\'s birthday', $from, $to)
        ->description('Cookies & cocktails!')
        ->address('Samberstraat 69D, 2060 Antwerpen');

// Generate a link to create an event on Google calendar
    $google= $link->google();

// Generate a link to create an event on Yahoo calendar
    $yahoo= $link->yahoo();

// Generate a link to create an event on outlook.com calendar
    $outlook= $link->webOutlook();

// Generate a data uri for an ics file (for iCal & Outlook)
    $ics= $link->ics();
    return compact('google','yahoo','outlook','ics');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable,HasRoles;


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','first_name','last_name'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

resources/views/users/create.blade.php
@extends('layouts.dashboard')

@section('content')

    <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <form action="{{route('users.store')}}" method="POST">
                    {{csrf_field()}}
                        <ul class="nav nav-tabs " role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home-1" role="tab" aria-controls="home-1" aria-selected="true">
                                    {{__('General Information')}}
                                </a>
                            </li>

                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane fade active show" id="home-1" role="tabpanel" aria-labelledby="home-tab">

                                <div class="row">
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="first_name ">{{__('First Name')}}</label>
                                            <input class="form-control  @error('first_name') is-invalid @enderror"
                                                   type="text"
                                                   name="first_name"
                                                   value="{{old('first_name')}}"

                                            >
                                            @error('first_name')
                                            <span class="invalid-feedback" role="alert">
                                                 <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group ">
                                            <label for="last_name">{{__('Last Name')}}</label>
                                            <input class="form-control @error('last_name') is-invalid @enderror"
                                                   type="text"
                                                   name="last_name"
                                                   value="{{old('last_name')}}"

                                            >
                                            @error('last_name')
                                            <span class="invalid-feedback" role="alert">
                                                 <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="email">{{__('Email')}}</label>
                                            <input class="form-control @error('email') is-invalid @enderror"
                                                   type="text"
                                                   name="email"
                                                   value="{{old('email')}}"
                                            >
                                            @error('email')
                                            <span class="invalid-feedback" role="alert">
                                                 <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>

                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="email">{{__('Temporarily Password')}}</label>
                                            <input class="form-control @error('password') is-invalid @enderror" type="text" name="password" >
                                            @error('password')
                                            <span class="invalid-feedback" role="alert">
                                                 <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>

                                </div>
                                <div class="row">
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="first_name ">{{__('Date Of Birth')}}</label>
                                            <input class="form-control  @error('date_of_birth') is-invalid @enderror" type="text"
                                                   name="date_of_birth"
                                                   value="{{old('date_of_birth')}}"
                                            >
                                            @error('date_of_birth')
                                            <span class="invalid-feedback" role="alert">
                                                 <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group ">
                                            <label for="role">{{__('Role')}}</label>
                                            <select class="form-control @error('role') is-invalid @enderror" type="text" name="role">
                                                @foreach($roles as $role)
                                                    <option value="{{$role->id}}">{{$role->name}}</option>
                                                @endforeach
                                            </select>
                                            @error('role')
                                            <span class="invalid-feedback" role="alert">
                                                 <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="card bg-light">
                                            <div class="card-body">
                                                <h2>Permissions</h2>
                                                <p>
                                                    @foreach($permissions->chunk(3) as $list)
                                                        <div class="row">
                                                             @foreach($list as $permission)
                                                                 <div class="col-md-4">
                                                                       <div class="form-group">
                                                                             <div class="form-check">
                                                                                 <label class="form-check-label">
                                                                                     <input type="checkbox"  value="{{$permission->id}}" name="permissions[]" class="form-check-input">
                                                                                     {{__($permission->name)}}
                                                                                     <i class="input-helper"></i></label>
                                                                             </div>

                                                                        </div>
                                                                 </div>
                                                             @endforeach
                                                        </div>
                                                    @endforeach
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <button type="submit" class="btn btn-sm btn-github float-right">{{__('Save')}}</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.dashboard')

@section('content')

    <div class="row">
        <div class="col-md-12 grid-margin ">
            <form action="{{route('users.update',$user)}}" method="POST">
                {{csrf_field()}}
                {{method_field('PUT')}}
            <div class="card">
                <div class="card-body">

                        <ul class="nav nav-tabs " role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home-1" role="tab" aria-controls="home-1" aria-selected="true">
                                    {{__('General Information')}}
                                </a>
                            </li>

                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane fade active show" id="home-1" role="tabpanel" aria-labelledby="home-tab">

                                <div class="row">
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="first_name ">{{__('First Name')}}</label>
                                            <input class="form-control  @error('first_name') is-invalid @enderror" type="text" name="first_name"
                                                   value="{{$user->first_name}}">
                                            @error('first_name')
                                            <span class="invalid-feedback" role="alert">
                                                 <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group ">
                                            <label for="last_name">{{__('Last Name')}}</label>
                                            <input class="form-control @error('last_name') is-invalid @enderror" type="text" name="last_name" value="{{$user->last_name}}">
                                            @error('last_name')
                                            <span class="invalid-feedback" role="alert">
                                                 <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="email">{{__('Email')}}</label>
                                            <input class="form-control @error('email') is-invalid @enderror" type="text" name="email"value="{{$user->email}}" >
                                            @error('email')
                                            <span class="invalid-feedback" role="alert">
                                                 <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>

                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="email">{{__('Temporarily Password')}}</label>
                                            <input class="form-control @error('email') is-invalid @enderror" type="text" name="password" >
                                            @error('password')
                                            <span class="invalid-feedback" role="alert">
                                                 <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>

                                </div>
                                <div class="row">
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="first_name ">{{__('Date Of Birth')}}</label>
                                            <input class="form-control  @error('date_of_birth') is-invalid @enderror"
                                                   type="text"
                                                   name="date_of_birth"
                                                   value="{{$user->date_of_birth}}">
                                            @error('date_of_birth')
                                            <span class="invalid-feedback" role="alert">
                                                 <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group ">
                                            <label for="role">{{__('Role')}}</label>
                                            <select class="form-control @error('role') is-invalid @enderror"
                                                    type="text"
                                                    name="role" >
                                                @foreach($roles as $role)
                                                    <option value="{{$role->id}}" {{$user->hasRole($role->id)?'selected':''}}>{{$role->name}}</option>
                                                @endforeach
                                            </select>
                                            @error('role')
                                            <span class="invalid-feedback" role="alert">
                                                 <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="card bg-light">
                                            <div class="card-body">
                                                <h2>Permissions</h2>
                                                <p>
                                                    @foreach($permissions->chunk(3) as $list)
                                                        <div class="row">
                                                             @foreach($list as $permission)
                                                                 <div class="col-md-4 col-sm-6">
                                                                       <div class="form-group">
                                                                             <div class="form-check">
                                                                                 <label class="form-check-label">
                                                                                     <input type="checkbox" name="permissions[]" class="form-check-input" value="{{$permission->id}}"
                                                                                           {{in_array($permission->id,$user_permissions)?'checked':''}}>
                                                                                     {{__($permission->name)}}
                                                                                     <i class="input-helper"></i></label>
                                                                             </div>

                                                                        </div>
                                                                 </div>
                                                             @endforeach
                                                        </div>
                                                    @endforeach
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>



                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-github float-right ">{{__('Update')}}</button>
                        </div>
                    </div>
                </div>
            </div>
            </form>
        </div>
    </div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.dashboard')

@section('content')
<div class="card">
    <div class="card-body table-responsive">
        <a class="btn btn-github float-right" href="{{route('users.create')}}">{{__('Add New System User')}}</a>

        <table class="table table-striped">
            <thead>
            <tr>
                <th>
                    {{__("Name")}}
                </th>
                <th>
                    {{__("Email")}}
                </th>
                <th>
                    {{__("Role")}}
                </th>
                <th>
                    {{__("Address")}}
                </th>
                <th>
                    {{__('Status')}}
                </th>
                <th>
                    {{__("Created At")}}
                </th>
                <th>
                    {{__('Actions')}}
                </th>
            </tr>
            </thead>
            <tbody>
            @foreach($users as $user)
                <tr>
                    <td>
                        {{$user->first_name}} {{$user->last_name}}
                    </td>
                    <td>
                        {{$user->email}}
                    </td>
                    <td>
                    {{$user->roles()->first()->name}}
                    </td>
                    <td>
                        @if($user->address)
                         {{$user->address->street}} ,{{$user->address->city}} {{$user->address->postal_code}}<br> {{$user->address->country}}
                        @endif
                    </td>
                    <td>
                        <label class="toggle-switch">
                            <input type="checkbox" checked="{{$user->status??0}}">
                            <span class="toggle-slider round"></span>
                        </label>
                    </td>
                    <td>
                        {{$user->created_at->format('d M Y h:m:s')}}
                    </td>
                    <td>
                        <a href="{{route('users.edit',['id'=>$user->id])}}" >
                            Edit
                        </a>

                    </td>
                </tr>
            @endforeach
            <tr>
                <td colspan="6" class="text-center">
                    {{$users->links()}}
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
@endsection