routes/web.php
<?php


use App\User;
use Illuminate\Support\Facades\Notification;
use Spatie\CalendarLinks\Link;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('locale')->group(function(){

    Route::get('welcome/{lang}','LocalController@index');
    Route::get('/', "WelcomeController@index");



    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/dashboard', function(){
        return view("layouts.dashboard");
    });

    Route::post('temp','FileUploaderController@store')->name('files.store');
    Route::get('files/{document}','FileDownloaderController@download')->name('files.download');
    Auth::routes(['verify' => true]);
    Route::group(["prefix"=>"admin_102019_xyz"],function(){
        Auth::routes(['verify' => true]);
    });

    Route::get('jobs/{job}/apply_form','JobApplicationController@show')->name('jobs.apply_form_for_doctors');
    Route::post('jobs/{job}/apply','JobApplicationController@apply')->name('jobs.apply_for_doctors');

    Route::group(["middleware"=>["auth"]],function (){
        //For doctor portal




    });
    Route::group(['middleware'=>['auth','Admin'], "prefix"=>"admin_102019_xyz"],function(){

        Route::get('/',"HomeController@index");//TODO: Check this route
        Route::get('/dash',"AdminDashboardController@index")->name('admin.dashboard');

        //jobs

        Route::get('jobs/{job}/notifications_form','JobNotificationController@show')->name('jobs.notifications_form');

        Route::get('job_applications','JobApplicationController@index')->name('jobs.applications');

        Route::get('jobs/{job}/apply_form','JobApplicationController@show')->name('jobs.apply_form');
        Route::resource('jobs','JobController');
        Route::get('create_jobs','JobController@create')->name('jobs.create');
        Route::get('list_jobs','JobController@index')->name('jobs.list');
        Route::get('overview_jobs','JobController@index')->name('jobs.overview');//TODO: check if we need this route, or change it

        Route::post('jobs/{job}/send_notification','JobNotificationController@notifyDoctors')->name('jobs.send_notifications');
        Route::post('practices/{practice}/send_notification','JobNotificationController@sendVerificationToPractice')->name('jobs.send_notification_to_practice');


        //practices
        route::get('practice_jobs_view','JobNotificationController@verif_form')->name('practices.jobs_view');

        route::get('practices/{practice}/jobs/{job}/confirm','PracticeMissionConfirmController@confirm_mission')->name('practices.confirm_mission');
        route::get('practices/{practice}/confirm_many_missions','PracticeMissionConfirmController@confirm_missions')->name('practices.confirm_missions');

        Route::resource('practices','PracticeController');
        route::get('create_practice','PracticeController@create')->name('practices.create');
        route::get('list_practices','PracticeController@index')->name('practices.list');




        //doctors

        Route::get('doctors_notifications','DoctorsNotificationController@notifications')->name('doctors.notifications.view');
        Route::post('doctors_notifications','DoctorsNotificationController@sendNotifications')->name('doctors.notifications.send');


        Route::resource('doctors','DoctorController');
        route::get('create_doctor','DoctorController@create')->name('doctors.create');
        //services
        Route::post('services/{service}/clone','ServiceAreaController@clone')->name('services.clone');

        Route::resource('services','ServiceAreaController');
        route::get('create_service','ServiceAreaController@create')->name('services.create');
        route::get('list_services','ServiceAreaController@index')->name('services.list');
        Route::resource('users','UserManagerController');


        Route::resource('specialities','SpecialityController');

        Route::resource('recipients','RecipientsController');
        Route::resource('recipients-2nd','Recipients2ndController');

        Route::resource('hotels','HotelController');

        Route::resource('facilities','FacilityController');


        Route::get('calendar','CalendarController@index')->name('calendar.view');

        Route::get('templates','EmailTemplateController@index')->name('templates.index');
        Route::get('create_template','EmailTemplateController@create')->name('templates.create');
        Route::get('edit_template/{template}','EmailTemplateController@edit')->name('templates.edit');
        Route::post('store_template','EmailTemplateController@store')->name('templates.store');
        Route::post('update_template','EmailTemplateController@update')->name('templates.update');
        Route::get('templates/{template}/files/{template_file}/delete','EmailTemplateController@deleteFile')->name('templates.files.delete');


        Route::get('send_email_form','SendEmailController@show')->name('email.show');
        Route::post('send_email','SendEmailController@send')->name('email.send');

        Route::get('send_service_email_form','SendServiceEmailController@show')->name('service_email.show');
        Route::post('send_service_email','SendServiceEmailController@send')->name('service_email.send');


        Route::get('jobs-fulfillment','JobFulfillmentController@index')->name('jobs.fulfillment');
        Route::get('jobs-fulfillment/{job}','JobFulfillmentController@show')->name('jobs.fulfillment.show');
        Route::get('jobs-fulfillment/{job}/send-pdf','JobFulfillmentController@sendPDF')->name('jobs.fulfillment.send-pdf');

        Route::get('sent-emails','SentEmailsController@index')->name('sent-emails.index');

        Route::get('practice_jobs_new','JobNotificationController@verificationNew')->name('practices.verification_new');
        Route::post('practice_jobs_new','JobNotificationController@verificationNewSend')->name('practices.verification_new.send');

    });




});


Route::get('links',function (){

return \App\Models\Job::with(["applications"])->paginate(10);

    $from = DateTime::createFromFormat('Y-m-d H:i', '2018-02-01 09:00');
    $to = DateTime::createFromFormat('Y-m-d H:i', '2018-02-01 18:00');

    $link = Link::create('Sebastian\'s birthday', $from, $to)
        ->description('Cookies & cocktails!')
        ->address('Samberstraat 69D, 2060 Antwerpen');

// Generate a link to create an event on Google calendar
    $google= $link->google();

// Generate a link to create an event on Yahoo calendar
    $yahoo= $link->yahoo();

// Generate a link to create an event on outlook.com calendar
    $outlook= $link->webOutlook();

// Generate a data uri for an ics file (for iCal & Outlook)
    $ics= $link->ics();
    return compact('google','yahoo','outlook','ics');
});

app/Models/Job.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Job extends Model
{
    use SoftDeletes;
    protected $table="missions";

    const PENDING=0;//verification was send to Practice and wait the confirmation
    const Verified=1;// Practice verified the mission
    const Assigned=2;// Job Was Assigned to doctor
    protected $fillable=[
        'start_date',
        'end_date',
        'time_frames',
        'tags',
        'created_by',
        'practice_id',
        'service_area_id',
        'notes',
        'additional_remuneration',
        'ab',
        'status',
        'verified_at',
        'verification_sent_at',
        'order'
    ];
    protected $casts = [
        'tags' => 'array',
        'time_frames'=>'array',
        'start_date'=>"datetime",
        "end_date"=>'datetime',
        'verified_at'=>"datetime",
        'verification_sent_at'=>"datetime"

    ];



    public function service_area(){
        return $this->belongsTo(ServiceArea::class);
    }


    public function practice(){
        return $this->belongsTo(Practice::class);
    }
    public function doctor(){
        return $this->belongsTo(Doctor::class);
    }
    public function fees(){
        return $this->hasMany(JobFee::class);
    }
    public function applications(){
        return $this->hasMany(JobApplication::class,'mission_id');
    }
    public function total_hours(){
        return $this->start_date->diffInHours($this->end_date);
    }
}

app/Http/Controllers/JobController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreJobRequest;
use App\Models\Doctor;
use App\Models\Job;
use App\Models\JobFee;
use App\Models\Practice;
use App\Models\ServiceArea;
use App\Models\Tag;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use MongoDB\Driver\Exception\ExecutionTimeoutException;

class JobController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Job[]|\Illuminate\Database\Eloquent\Collection
     */
    public function index(Request $request)
    {
        $practice=Practice::find($request->input("p_id"));
        $service=ServiceArea::find($request->input("s_id"));
        $status=$request->input('status',null);
        return view('jobs.index',compact('practice','status','service'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $tags=Tag::all();
        return view('jobs.create',compact('tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return Job
     */
    public function store(StoreJobRequest $request)
    {

       // return Carbon::createFromFormat("d.m.Y H:m",$request->input("start_date"))->toDateTimeString();

        $tags=json_decode($request->input('tags'));



        if(is_array($tags)){
            foreach ($tags as $tag){
                if(!array_key_exists('id',$tag)){
                    Tag::firstOrCreate(['value'=>$tag->value]);
                }

            }
        }
        $job=new Job;
        $job->fill($request->only('practice_id','service_area_id','notes','additional_remuneration','ab'));
        $job->start_date=Carbon::createFromFormat("d.m.Y H:i",$request->input("start_date"));
        $job->end_date=Carbon::createFromFormat("d.m.Y H:i",$request->input("end_date"));

        $job->tags=$tags;
        $time_frames=[];
        try{
            $to=$request->input("to",[]);
            $notes=$request->input("notes",[]);
            $per_hours=$request->input("per_hour",[]);

            foreach ($request->input('from',[]) as $index=>$from){
                    $time_frames[]=[
                        "from"=>Carbon::createFromFormat("d.m.Y H:i",$from),
                        "to"=>Carbon::createFromFormat("d.m.Y H:i",$to[$index]),
                        "per_hour"=>$per_hours[$index],
                        "notes"=>$notes[$index]
                    ];
            }

        }catch (\Exception $ex){

        }
        $job->time_frames=$time_frames;

        $job->created_by=Auth::user()->id;

        $job->save();

        return redirect()->route('jobs.show',$job)->with(['message'=>"job successfully created"]);


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Job $job)
    {


        $doctors = Doctor::with([
            'user' => function ($q) {
                $q->select('id', 'first_name', 'last_name', 'email');
            }])
            ->get(["id", "user_id"]);

        return view('jobs.show',compact('job','doctors'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Job $job)
    {


        $tags=Tag::all();
        return view('jobs.edit',compact('tags','job'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param Job $job
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Job $job)
    {



        $tags=json_decode($request->input('tags'));

        $time_frames=json_decode($request->input('frames'));
        if(is_array($tags)){
            foreach ($tags as $tag){
                Tag::firstOrCreate(['value'=>$tag->value]);
            }
        }

        $job->update($request->only('practice_id','service_area_id','notes','additional_remuneration','ab'));
        $job->start_date=$request->input("start_date").":00";
        $job->end_date=$request->input("end_date").":00";
        $job->tags=$tags;
        $job->time_frames=$time_frames;
        $job->save();

        return redirect()->route('jobs.show',$job)->with(['message'=>"job successfully updated"]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/jobs/fulfillment-details.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="card">
        <div class="card-header">
            {{__('Job Fulfillment details')}}
        </div>
        <strong>{{isset($message)?$message:''}}</strong>
        <div class="card-body">

            <div class="row">
                <div class="col-md-1">{{__("Start Date")}}:</div>
                <div class="col-md-2">{{$job->start_date->format('d.m.Y H:m')}}</div>
                <div class="col-md-1">{{__("End Date")}}:</div>
                <div class="col-md-2">{{$job->end_date->format('d.m.Y H:m')}}</div>
            </div>
            <div class="row">
                <div class="col-md-1">{{__("Service Area")}}:</div>
                <div class="col-md-2">{{$job->service_area->name}}</div>
                <div class="col-md-1">{{__("Hours")}}:</div>
                <div class="col-md-2">{{$job->total_hours()}} h</div>
            </div>
            <div class="row">
                <div class="col-md-1">{{__("Doctor Name")}}:</div>
                <div class="col-md-2">{{$job->doctor->user->first_name}} {{$job->doctor->user->last_name}}</div>
                <div class="col-md-1">{{__("Practice Name")}}:</div>
                <div class="col-md-2">{{$job->practice->first_name}} {{$job->practice->last_name}}</div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <form action="{{route('jobs.fulfillment.send-pdf',$job->id)}}" method="get">
                        <button type="submit" class="btn btn-github float-right">{{__('Send PDF')}}</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('js')

@endsection

resources/views/jobs/fulfillment.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="card">
        <div class="card-body table-responsive">

            <table class="table table-striped">
                <thead>
                <tr>
                    <th>
                        {{__("Start Date")}}
                    </th>
                    <th>
                        {{__("End Date")}}
                    </th>
                    <th>
                        {{__("Service Area")}}
                    </th>
                    <th>
                        {{__("Doctor Name")}}
                    </th>
                    <th>
                        {{__("Practice Name")}}
                    </th>
                    <th>
                        {{__("Actions")}}
                    </th>
                </tr>
                </thead>
                <tbody>
                @foreach($jobs as $job)
                    <tr>
                        <td>
                            {{$job->start_date->format('d.m.Y H:m')}}
                        </td>
                        <td>
                            {{$job->end_date->format('d.m.Y H:m')}}
                        </td>
                        <td>
                            {{$job->service_area->name}}
                        </td>
                        <td>
                            {{$job->doctor->user->first_name}} {{$job->doctor->user->last_name}}
                        </td>
                        <td>
                            {{$job->practice->first_name}} {{$job->practice->last_name}}
                        </td>
                        <td>
                            <a href="{{route('jobs.fulfillment.show',$job->id)}}">{{__("Details")}}</a>
                        </td>
                    </tr>
                @endforeach
                <tr>
                    <td colspan="6" class="text-center">
                        {{$jobs->links()}}
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

@endsection

@section('js')

@endsection

resources/views/jobs/index.blade.php
@extends('layouts.dashboard')
@section('head')
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/jq-3.3.1/dt-1.10.18/af-2.3.3/b-1.5.6/sc-2.0.0/sl-1.3.0/datatables.min.css"/>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/css/select2.min.css" rel="stylesheet" />

    <style>
        .filter-wrapper.form-group.form-control {
            border-radius: 4px!important;
            border: 1px solid #eee !important;
        }

    </style>
@endsection
@section('content')

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body ">
                    <form action="{{route("jobs.list")}}" method="get" id="form-filter">
                    <div class="filter-wrapper row" style="">
                        <div class="col-md-1 ">
                            <div class="form-group jobs_length">
                                <label for="">{{__('Show')}}</label>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group" style="margin-bottom: 1px">
                                <label for="">{{__('Practice')}}</label>
                                <select name="p_id" id="p_id" class="form-control">
                                    <option value=""></option>
                                    @if($practice)
                                        <option value="{{$practice->id}} " selected>{{$practice->fullName()}}</option>
                                    @endif
                                </select>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group" style="margin-bottom: 1px">
                                <label for="">{{__('Service Area')}}</label>
                                <select name="s_id" id="s_id" class="form-control">

                                    @if($practice)

                                        @foreach($practice->service_areas as $service_area)
                                          <option value="{{$service_area->id}}" selected>{{$service_area->name}}</option>
                                        @endforeach
                                    @endif
                                </select>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group" style="margin-bottom: 1px">
                                <label for="">{{__('Job Status')}}</label>
                                <select name="status" id="j_status" class="form-control">
                                    <option value="" {{$status===null?'selected':''}}>{{__('All')}}</option>
                                    <option value="0" {{$status==='0'?'selected':''}}>{{__('Unverified Jobs')}}</option>
                                    <option value="1" {{$status==1?'selected':''}}>{{__('Verified Jobs')}}</option>
                                    <option value="2" {{$status==2?'selected':''}}>{{__('Assigned Jobs')}}</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-5">
                                <div class="form-group search-field">
                                    <label for="">{{__('Search')}}</label>
                                </div>
                        </div>


                    </div>
                    </form>
                    <table class="table  table-striped table-hover" id="jobs-datatable" style="width: 100%; ">
                             <thead>
                             <tr>
                                 <th>

                                 </th>
                                 <th>
                                     {{__('Start Date')}}
                                 </th>
                                 <th>
                                     {{__('End Date')}}
                                 </th>

                                 <th>
                                     {{__('Practice')}}
                                 </th>
                                 <th>
                                     {{__('Service Area')}}
                                 </th>
                                 <th>
                                     {{__('status')}}
                                 </th>
                                 <th>
                                     {{__('Updated At')}}
                                 </th>
                                 <th>

                                 </th>
                             </tr>
                             </thead>
                             <tbody>

                             </tbody>
                         </table>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/jq-3.3.1/dt-1.10.18/af-2.3.3/b-1.5.6/sc-2.0.0/sl-1.3.0/datatables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/js/select2.min.js"></script>
    <!--
   <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>
 -->
    <script>

        var chunck=function(str, n) {
            var ret = [];
            var i;
            var len;

            for(i = 0, len = str.length; i < len; i += n) {
                ret.push(str.substr(i, n))
            }

            return ret
        };
        $(document).ready( function () {
            let p_name=$('#p-name').val()
            $('#jobs-datatable').DataTable({
                "processing": true,
                "iDisplayLength": 50,
                "serverSide": true,
                @if($practice)
                "ajax": "{{ route('datatable.jobs.index') }}?p_id={{$practice->id}}&status={{$status}}&s_id={{$service?$service->id:''}}",
                @else
                "ajax": "{{ route('datatable.jobs.index') }}?status={{$status}}",
                @endif
                "columns": [
                    {
                        "data":"id",
                        "name":"id",
                        "render":function(d){

                            return  `<div class="form-check mb-0 mt-0">
                                 <label class="form-check-label">
                                 <input type="checkbox" name="jobs_ids[]" class="form-check-input" value="${d}" >
                               <i class="input-helper"></i></label>
                            </div>`
                        }

                    },
                    {   "data": "start_date" ,
                        'name':"start_date",
                        "render": function(d) {

                            return moment(d).format("DD.MM.YYYY HH:mm ")

                        }

                    },
                    {   "data": "end_date" ,
                        'name':"end_date",
                        "render": function(d) {

                            return moment(d).format("DD.MM.YYYY HH:mm ")

                        }

                    },
                    {
                        "data": "practice" ,
                        'name':"practice.first_name",
                        "defaultContent":"<i class='text-google'>Not Set</i>",
                        "render": function(d) {

                           if(d!=null){

                              return "<a href='{{route('practices.index')}}/"+d.id+"/edit'>"+d.first_name + ' ' + d.last_name+"</a>"

                           }

                        }

                    },
                    {   "data": "service_area",
                        'name':"service_area.name",
                        "defaultContent":"<i class='text-google'>Not Set</i>",
                        "render": function(d) {

                            if(d!=null){
                                return  d.name
                            }

                        }

                    },
                    {
                        data:"status",
                        name:"status",
                        defaultContent:" <i class='mdi mdi-check'></i>",
                        "render":function(d){
                            /*
                            *
                            * const PENDING=0;//verification was send to Practice and wait the confirmation
                            *  const Verified=1;// Practice verified the mission
                            *     const Assigned=2
                            * */
                           if(d!=null){

                                if(status==='0') {
                                    return "Send Verification to practice?"
                                }
                                if(d==='1'){
                                    return "<span class='badge badge-info'><i class='mdi mdi-check'> {{__('Confirmed')}} </span>"
                                }
                               if(d==='2'){
                                   return "<span class='badge badge-danger'><i class='mdi mdi-check'>{{__('Assigned')}} </span>"
                               }

                           }
                          return `<button class="btn btn-xs btn-facebook">{{__('Send Verification')}}</button>`
                        }
                    },
                    {
                        "data":"updated_at",
                        "render":function (d) {
                            return moment(d).format("DD.MM.YYYY HH:mm")
                        }
                    },
                    {
                        "data":null,
                        "name":"id",
                        "render":function (d) {

                            var actions= '<a class=""  href="{{route('jobs.index')}}/'+d.id+'">{{__('Details')}}</a>';





                            return actions






                        }
                    }


                ]
            });

            $('#p_id').select2({
                theme: "classic",
                allowClear: true,
                placeholder: "{{__('Select a practice')}}",
                ajax: {
                    url: '{{route('microservices.practices.search')}}',
                    data: function (params) {
                        var query = {
                            q: params.term,

                        }

                        // Query parameters will be ?search=[term]&type=public
                        return query;
                    },
                    processResults: function (data) {
                        // Transforms the top-level key of the response object from 'items' to 'results'
                        return {
                            results:  $.map(data, function (item) {
                                return {
                                    text: item.first_name+' '+item.last_name,
                                    id: item.id
                                }
                            })
                        };
                    },
                    dataType: 'json'
                    // Additional AJAX parameters go here; see the end of this chapter for the full code of this example
                }
            });


            $('#j_status').select2({
                theme:"classic",
                 minimumResultsForSearch: -1
            })

            $('#s_id').select2({
                theme:"classic",
                placeholder:'{{__('Select Service Area')}}',
                allowClear: true,

            })
            $('.jobs_length').append($("#jobs-datatable_length select"))

            $('.search-field').append($("#jobs-datatable_filter input"))
            $('#jobs-datatable_wrapper div:first').remove()
            $('.jobs_length select').removeClass("custom-select").removeClass("custom-select-sm").css('padding',"0px")
            $('[name="jobs-datatable_length"]').select2({
                theme:"classic",
                minimumResultsForSearch: -1
            })
            $('#s_id').on('select2:select', function (e) {
                $('#form-filter').submit()
            });
            $('#p_id').on('select2:select', function (e) {
               $('#form-filter').submit()
            });
            $('#p_id').on('select2:clear', function (e) {
                $('#form-filter').submit()
            });
            $('#j_status').on('select2:select', function (e) {
                $('#form-filter').submit()
            });
        });
    </script>
@endsection