routes/web.php
<?php


use App\User;
use Illuminate\Support\Facades\Notification;
use Spatie\CalendarLinks\Link;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('locale')->group(function(){

    Route::get('welcome/{lang}','LocalController@index');
    Route::get('/', "WelcomeController@index");



    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/dashboard', function(){
        return view("layouts.dashboard");
    });

    Route::post('temp','FileUploaderController@store')->name('files.store');
    Route::get('files/{document}','FileDownloaderController@download')->name('files.download');
    Auth::routes(['verify' => true]);
    Route::group(["prefix"=>"admin_102019_xyz"],function(){
        Auth::routes(['verify' => true]);
    });

    Route::get('jobs/{job}/apply_form','JobApplicationController@show')->name('jobs.apply_form_for_doctors');
    Route::post('jobs/{job}/apply','JobApplicationController@apply')->name('jobs.apply_for_doctors');

    Route::group(["middleware"=>["auth"]],function (){
        //For doctor portal




    });
    Route::group(['middleware'=>['auth','Admin'], "prefix"=>"admin_102019_xyz"],function(){

        Route::get('/',"HomeController@index");//TODO: Check this route
        Route::get('/dash',"AdminDashboardController@index")->name('admin.dashboard');

        //jobs

        Route::get('jobs/{job}/notifications_form','JobNotificationController@show')->name('jobs.notifications_form');

        Route::get('job_applications','JobApplicationController@index')->name('jobs.applications');

        Route::get('jobs/{job}/apply_form','JobApplicationController@show')->name('jobs.apply_form');
        Route::resource('jobs','JobController');
        Route::get('create_jobs','JobController@create')->name('jobs.create');
        Route::get('list_jobs','JobController@index')->name('jobs.list');
        Route::get('overview_jobs','JobController@index')->name('jobs.overview');//TODO: check if we need this route, or change it

        Route::post('jobs/{job}/send_notification','JobNotificationController@notifyDoctors')->name('jobs.send_notifications');
        Route::post('practices/{practice}/send_notification','JobNotificationController@sendVerificationToPractice')->name('jobs.send_notification_to_practice');


        //practices
        route::get('practice_jobs_view','JobNotificationController@verif_form')->name('practices.jobs_view');

        route::get('practices/{practice}/jobs/{job}/confirm','PracticeMissionConfirmController@confirm_mission')->name('practices.confirm_mission');
        route::get('practices/{practice}/confirm_many_missions','PracticeMissionConfirmController@confirm_missions')->name('practices.confirm_missions');

        Route::resource('practices','PracticeController');
        route::get('create_practice','PracticeController@create')->name('practices.create');
        route::get('list_practices','PracticeController@index')->name('practices.list');




        //doctors

        Route::get('doctors_notifications','DoctorsNotificationController@notifications')->name('doctors.notifications.view');
        Route::post('doctors_notifications','DoctorsNotificationController@sendNotifications')->name('doctors.notifications.send');


        Route::resource('doctors','DoctorController');
        route::get('create_doctor','DoctorController@create')->name('doctors.create');
        //services
        Route::post('services/{service}/clone','ServiceAreaController@clone')->name('services.clone');

        Route::resource('services','ServiceAreaController');
        route::get('create_service','ServiceAreaController@create')->name('services.create');
        route::get('list_services','ServiceAreaController@index')->name('services.list');
        Route::resource('users','UserManagerController');


        Route::resource('specialities','SpecialityController');

        Route::resource('recipients','RecipientsController');
        Route::resource('recipients-2nd','Recipients2ndController');

        Route::resource('hotels','HotelController');

        Route::resource('facilities','FacilityController');


        Route::get('calendar','CalendarController@index')->name('calendar.view');

        Route::get('templates','EmailTemplateController@index')->name('templates.index');
        Route::get('create_template','EmailTemplateController@create')->name('templates.create');
        Route::get('edit_template/{template}','EmailTemplateController@edit')->name('templates.edit');
        Route::post('store_template','EmailTemplateController@store')->name('templates.store');
        Route::post('update_template','EmailTemplateController@update')->name('templates.update');
        Route::get('templates/{template}/files/{template_file}/delete','EmailTemplateController@deleteFile')->name('templates.files.delete');


        Route::get('send_email_form','SendEmailController@show')->name('email.show');
        Route::post('send_email','SendEmailController@send')->name('email.send');

        Route::get('send_service_email_form','SendServiceEmailController@show')->name('service_email.show');
        Route::post('send_service_email','SendServiceEmailController@send')->name('service_email.send');


        Route::get('jobs-fulfillment','JobFulfillmentController@index')->name('jobs.fulfillment');
        Route::get('jobs-fulfillment/{job}','JobFulfillmentController@show')->name('jobs.fulfillment.show');
        Route::get('jobs-fulfillment/{job}/send-pdf','JobFulfillmentController@sendPDF')->name('jobs.fulfillment.send-pdf');

        Route::get('sent-emails','SentEmailsController@index')->name('sent-emails.index');

        Route::get('practice_jobs_new','JobNotificationController@verificationNew')->name('practices.verification_new');
        Route::post('practice_jobs_new','JobNotificationController@verificationNewSend')->name('practices.verification_new.send');

    });




});


Route::get('links',function (){

return \App\Models\Job::with(["applications"])->paginate(10);

    $from = DateTime::createFromFormat('Y-m-d H:i', '2018-02-01 09:00');
    $to = DateTime::createFromFormat('Y-m-d H:i', '2018-02-01 18:00');

    $link = Link::create('Sebastian\'s birthday', $from, $to)
        ->description('Cookies & cocktails!')
        ->address('Samberstraat 69D, 2060 Antwerpen');

// Generate a link to create an event on Google calendar
    $google= $link->google();

// Generate a link to create an event on Yahoo calendar
    $yahoo= $link->yahoo();

// Generate a link to create an event on outlook.com calendar
    $outlook= $link->webOutlook();

// Generate a data uri for an ics file (for iCal & Outlook)
    $ics= $link->ics();
    return compact('google','yahoo','outlook','ics');
});

app/Http/Controllers/Recipients2ndController.php
<?php


namespace App\Http\Controllers;


use App\Models\Recipient2nd;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class Recipients2ndController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {

        $recipients = Recipient2nd::paginate(10);

        return view('recipients-2nd.index', compact('recipients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('recipients-2nd.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'first_name' => "required",
            'last_name' => "required",
            'email' => "required|email",
        ]);
        Recipient2nd::create($request->only(['first_name', 'last_name', 'email']));
        return redirect()->route('recipients-2nd.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Recipient2nd $recipient
     * @return void
     * @throws \Exception
     */
    public function destroy( $recipientID)
    {
        $recipient=Recipient2nd::find($recipientID);
        $recipient->delete();
        return redirect()->back()->with(['message' => "Recipient deleted"]);
    }
}

resources/views/recipients-2nd/create.blade.php
@extends('layouts.dashboard')

@section('content')
    @if($errors->count())
        <div class="alert alert-warning">
            {{$errors->first()}}
        </div>

    @endif
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        {{__('Create New Recipient - Interessenten')}}
                    </div>

                    <div class="card-body">

                        <form action="{{route('recipients-2nd.store')}}" method="POST">
                            {{csrf_field()}}
                            <div class="row">
                                <div class="col-md-4 col-sm-6 col-lg-4">
                                    <div class="form-group">
                                        <label for="">{{__('First Name')}}</label>
                                        <input type="text" class="form-control" name="first_name" value="{{old('first_name')}}">
                                    </div>
                                </div>
                                <div class="col-md-4 col-sm-6 col-lg-4">
                                    <div class="form-group">
                                        <label for="">{{__('Last Name')}}</label>
                                        <input type="text" class="form-control" name="last_name" value="{{old('last_name')}}">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4 col-sm-6 col-lg-4">
                                    <div class="form-group">
                                        <label for="">{{__('Email')}}</label>
                                        <input type="text" class="form-control" name="email" value="{{old('email')}}">
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <button class="btn btn-github float-right">{{__('Save')}}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/recipients-2nd/index.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="card">
        <div class="card-body table-responsive">
            <a class="btn btn-github float-right"
               href="{{route('recipients-2nd.create')}}">{{__('Add New Recipient - Interessenten')}}</a>

            <table class="table table-striped">
                <thead>
                <tr>
                    <th>
                        {{__("First Name")}}
                    </th>
                    <th>
                        {{__("Last Name")}}
                    </th>
                    <th>
                        {{__("Email")}}
                    </th>

                    <th>
                        {{__("Created At")}}
                    </th>
                    <th>
                        {{__('Actions')}}
                    </th>
                </tr>
                </thead>
                <tbody>
                @foreach($recipients as $recipient)
                    <tr>
                        <td>
                            {{$recipient->first_name}}
                        </td>
                        <td>
                            {{$recipient->last_name}}
                        </td>
                        <td>
                            {{$recipient->email}}
                        </td>

                        <td>
                            {{$recipient->created_at ? $recipient->created_at->format('d M Y h:m:s') : ''}}
                        </td>
                        <td>
                            <form method="POST" action="{{route('recipients-2nd.destroy',['id'=>$recipient->id])}}"
                                  id="id_{{$recipient->id}}">
                                {{csrf_field()}} {{method_field("DELETE")}}
                                <a href="#"
                                   onclick="document.getElementById('id_{{$recipient->id}}').submit()">{{__('Delete')}}</a>
                            </form>

                        </td>
                    </tr>
                @endforeach
                <tr>
                    <td colspan="6" class="text-center">
                        {{$recipients->links()}}
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

@endsection

@section('js')

@endsection